# SPDX-License-Identifier: Apache-2.0
# BF16 thinker-only profile for the MMMU CI stage (2 DP replicas behind the router).
config_cls: Qwen3OmniPipelineConfig
name: qwen3-omni-mmmu-h100
model_path: Qwen/Qwen3-Omni-30B-A3B-Instruct
relay_backend: shm

stage_overrides:
  image_encoder:
    runtime:
      resources:
        total_gpu_memory_fraction: 0.03

  audio_encoder:
    runtime:
      resources:
        total_gpu_memory_fraction: 0.03

  thinker:
    runtime:
      resources:
        total_gpu_memory_fraction: 0.92
